version: '3'

services:
  servidor1:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./registro_log:/app/registro_log

  servidor2:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./registro_log:/app/registro_log

  servidor3:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./registro_log:/app/registro_log
