# Usando uma imagem base Python
FROM python:3.9-slim-buster

# Configura o diretório de trabalho
WORKDIR /app

# Copia o arquivo de requisitos
COPY requirements.txt requirements.txt

# Instala os pacotes Python necessários
RUN pip install -r requirements.txt

# Copia o código fonte para o diretório de trabalho
COPY . .

# Expõe a porta em que a aplicação irá rodar
EXPOSE 5000

# Comando para iniciar a aplicação
CMD ["python", "api.py"]
