version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTANCE_NUMBER=1
    ports:
      - '5000:5000'
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTANCE_NUMBER=2
    ports:
      - '5001:5000'
  server3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTANCE_NUMBER=3
    ports:
      - '5002:5000'
